RESULTS_FOLDER = "results"
LATENCY_GRAPH_FILE = "latency_percentiles.png"
LLM_REQUESTS_FILE = "llm_requests.csv"
NETWORK_LATENCY_FILE = "network_latency.csv"
ENDPOINT_SPEC_FILE = "endpoint_spec.yml"
RUN_SUITE_FILE = "run_suite.yml"
ERROR_FILE = "error.log"
SUMMARY_FILE = "summary.yml"
REQUESTS_PER_SECOND_COLUMN_NAME = "requests_per_second_at_the_time"

MAX_INPUT_TOKENS_ENV_VAR = "TOKENFLOOD_MAX_INPUT_TOKENS"
MAX_OUTPUT_TOKENS_ENV_VAR = "TOKENFLOOD_MAX_OUTPUT_TOKENS"

MAX_INPUT_TOKENS_DEFAULT = 1000000
MAX_OUTPUT_TOKENS_DEFAULT = 10000

WARNING_LIMIT = 0.1
