RESULTS_FOLDER = "results"
LLM_REQUESTS_FILE = "llm_requests.csv"
NETWORK_LATENCY_FILE = "network_latency.csv"
ENDPOINT_SPEC_FILE = "endpoint.yml"
LOAD_TEST_SPEC_FILE = "load_test.yml"
OBSERVATION_SPEC_FILE = "observation.yml"
ERROR_FILE = "errors.csv"
REQUESTS_PER_SECOND_COLUMN_NAME = "requests_per_second_at_the_time"

CLIENT_SESSION_INIT_BACKUP_ATTR = "_tokenflood_init_backup"

COMMON_RESULT_FILES = {
    LLM_REQUESTS_FILE,
    NETWORK_LATENCY_FILE,
    ENDPOINT_SPEC_FILE,
    ERROR_FILE,
}

LOAD_TEST_RESULT_FILES = {LOAD_TEST_SPEC_FILE}

OBSERVATION_RESULT_FILES = {OBSERVATION_SPEC_FILE}

WARNING_LIMIT = 0.1
WARNING_LIMIT_PERCENTAGE = WARNING_LIMIT * 100
DEFAULT_ERROR_RATE_LIMIT = 0.3
ERROR_RING_BUFFER_SIZE = 30

DEFAULT_PERCENTILES_STR = "95, 99"

DEFAULT_HEURISTIC_TASK = "Task: Write a 3-page essay on Popperian falsification."
DEFAULT_PROMPT_FILLER_TOKENS = tuple([" " + chr(c) for c in range(65, 91)])
